''''
Store the following DNA sequence in a variable

dna = AAGGTAAGTTTAGAATATATATATAAAAGGTGAGTTAAATAGAATAGGTTAAAATTAAAGGAGATCAGATCAGATCAGATCTATCTATCTATCTATCTATCAGAAAAGAGTAAATAGTTAAAGAGTAAGATATTGAATTAATGGAAAATATTGTTGGGGAAAGGAGGGATAGAAGG

Count how many of the following string

sequence = AT

we have in DNA

'''

def consec_repeats(sequence, dna):
    i = 0
    while sequence*(i+1) in dna:
        i += 1
    return i

dna = "AAGGTAAGTTTAGAATATATATATATATAAAAGGTGAGTTAAATAGAATAGGTTAAAATTAAAGGAGATCAGATCAGATCAGATCTATCTATCTATCTATCTATCAGAAAAGAGTAAATAGTTAAAGAGTAAGATATTGAATTAATGGAAAATATTGTTGGGGAAAGGAGGGATAGAAGG"
sequence = "AT"

print(consec_repeats(sequence, dna))


